# Site settings
title: Multicolour - Rest API generator
email: hello@newworld.codes
description: Generate a NodeJS REST API for your apps, games and in minutes using Multicolour rest api generator.
keywords: multicolour, rest api, generator, nodejs
baseurl: ""
url: "https://getmulticolour.com"
twitter_username: getmulticolour
facebook_username: getmulticolour
publisher: New World Code Ltd
mailchimp_uri: https://getmulticolour.us12.list-manage.com/subscribe/post?u=bec938217586432b04e1ea290&amp;id=e5a068eb80
latest_version: '0.6.3'
analytics_key: Qurt0kpTtzocuF8h8VgRH6ygztdQPK5i
year: 2017

# Custom collections like docs.
collections:
  examples:
    output: true
    output_ext: .html
  docs:
    output: true
    output_ext: .html
    permalink: /:collection/:path/:title

# List of documented versions.
versions:
  - "0.6.3"

# Sitemap settings.
sitemap:
  docs: 2017-03-03T12:49:30-05:00
  pages: 2017-03-03T12:49:30-05:00
  examples: 2017-03-03T12:49:30-05:00

# Build settings
markdown: kramdown

# Kramdown settings
kramdown:
  auto_ids: true
